//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqExtensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqExtensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exceptionApplyAttempt {
            get {
                return ResourceManager.GetString("exceptionApplyAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exceptionMatchType {
            get {
                return ResourceManager.GetString("exceptionMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exceptionMissingFieldOrProperty {
            get {
                return ResourceManager.GetString("exceptionMissingFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excption2DFlip {
            get {
                return ResourceManager.GetString("excption2DFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excption3DFlip {
            get {
                return ResourceManager.GetString("excption3DFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excption3DRotation {
            get {
                return ResourceManager.GetString("excption3DRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excption4DFlip {
            get {
                return ResourceManager.GetString("excption4DFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excption4DRotation {
            get {
                return ResourceManager.GetString("excption4DRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionDynamicPropertyAccess {
            get {
                return ResourceManager.GetString("excptionDynamicPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidAngle {
            get {
                return ResourceManager.GetString("excptionInvalidAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidAxis {
            get {
                return ResourceManager.GetString("excptionInvalidAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidGenerateGenericType {
            get {
                return ResourceManager.GetString("excptionInvalidGenerateGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidItemsCount {
            get {
                return ResourceManager.GetString("excptionInvalidItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidNoiseFilterType {
            get {
                return ResourceManager.GetString("excptionInvalidNoiseFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidNoiseFilterTypeLimits {
            get {
                return ResourceManager.GetString("excptionInvalidNoiseFilterTypeLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidRangeGenericType {
            get {
                return ResourceManager.GetString("excptionInvalidRangeGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidSkipCount {
            get {
                return ResourceManager.GetString("excptionInvalidSkipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionInvalidTakeCount {
            get {
                return ResourceManager.GetString("excptionInvalidTakeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionParamMaxRange {
            get {
                return ResourceManager.GetString("excptionParamMaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionParamMinRange {
            get {
                return ResourceManager.GetString("excptionParamMinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionRoundingDigits {
            get {
                return ResourceManager.GetString("excptionRoundingDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionSequenceMinOne {
            get {
                return ResourceManager.GetString("excptionSequenceMinOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionSequenceMinTwo {
            get {
                return ResourceManager.GetString("excptionSequenceMinTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionSequenceMinTwoNotNull {
            get {
                return ResourceManager.GetString("excptionSequenceMinTwoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionSourceSequenceIsNull {
            get {
                return ResourceManager.GetString("excptionSourceSequenceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionStepDuration {
            get {
                return ResourceManager.GetString("excptionStepDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionValueMinBlockSize {
            get {
                return ResourceManager.GetString("excptionValueMinBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string excptionValueMinTwo {
            get {
                return ResourceManager.GetString("excptionValueMinTwo", resourceCulture);
            }
        }
    }
}
